<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../contracts/1.0/workflow.schema.json"
                      LogicalName="AirlineDemo.Generator.Contracts.workflow.schema.json" />
    <EmbeddedResource Include="../../contracts/1.0/openapi.json"
                      LogicalName="AirlineDemo.Generator.Contracts.openapi.json" />
  </ItemGroup>

</Project>
